from __future__ import annotations

from datetime import datetime
from html import escape

from dailynews.summarize.brief import DailyBrief


def email_subject(brief: DailyBrief) -> str:
    generated = _format_date(brief.generated_at)
    count = len(brief.stories)
    label = "story" if count == 1 else "stories"
    return f"DNA Daily Brief | {generated} | {count} {label}"


def render_email(brief: DailyBrief) -> str:
    story_rows = "".join(_render_story(index, story) for index, story in enumerate(brief.stories, 1))
    source_names = sorted({story.source_name for story in brief.stories if story.source_name})
    sources = " &bull; ".join(escape(source) for source in source_names)
    preheader = escape(brief.executive_summary[:140])
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{escape(email_subject(brief))}</title>
</head>
<body style="margin:0;padding:0;background:#f3f4f6;color:#171717;font-family:Arial,Helvetica,sans-serif;">
  <div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;">{preheader}</div>
  <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background:#f3f4f6;">
    <tr><td align="center" style="padding:24px 12px;">
      <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="max-width:680px;background:#ffffff;border:1px solid #e5e7eb;">
        <tr><td style="padding:28px 32px 24px;background:#171717;color:#ffffff;">
          <div style="font-size:12px;font-weight:700;letter-spacing:1.5px;color:#f87171;">DNA DAILY BRIEF</div>
          <h1 style="margin:12px 0 8px;font-size:28px;line-height:1.2;font-weight:700;letter-spacing:0;">{escape(brief.headline)}</h1>
          <div style="font-size:13px;color:#d1d5db;">{escape(_format_date(brief.generated_at))} &bull; {len(brief.stories)} ranked stories</div>
        </td></tr>
        <tr><td style="padding:28px 32px 8px;">
          <div style="border-left:4px solid #dc2626;padding:4px 0 4px 16px;">
            <div style="font-size:12px;font-weight:700;letter-spacing:1px;color:#991b1b;margin-bottom:8px;">TODAY IN AI</div>
            <p style="margin:0;font-size:16px;line-height:1.65;color:#374151;">{escape(brief.executive_summary)}</p>
          </div>
        </td></tr>
        {story_rows}
        <tr><td style="padding:24px 32px;background:#f9fafb;border-top:1px solid #e5e7eb;">
          <div style="font-size:11px;font-weight:700;letter-spacing:1px;color:#6b7280;margin-bottom:8px;">TODAY'S SOURCES</div>
          <div style="font-size:13px;line-height:1.5;color:#4b5563;">{sources}</div>
          <div style="margin-top:18px;font-size:11px;line-height:1.5;color:#9ca3af;">Generated by DNA Daily News Agent. Summaries are grounded in the linked source material.</div>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>"""


def _render_story(index: int, story) -> str:
    why = ""
    if story.why_it_matters:
        why = f'<p style="margin:12px 0 0;font-size:14px;line-height:1.55;color:#4b5563;"><strong>Why it matters:</strong> {escape(story.why_it_matters)}</p>'
    link = escape(story.source_url, quote=True)
    source_link = (
        f'<a href="{link}" style="color:#b91c1c;text-decoration:none;font-weight:700;">Read source &rarr;</a>'
        if story.source_url
        else escape(story.source_name)
    )
    return f"""
        <tr><td style="padding:24px 32px;border-top:1px solid #e5e7eb;">
          <table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr>
            <td valign="top" width="38" style="padding-right:14px;">
              <div style="width:30px;height:30px;line-height:30px;text-align:center;background:#fee2e2;color:#991b1b;font-size:13px;font-weight:700;">{index}</div>
            </td>
            <td valign="top">
              <h2 style="margin:0 0 8px;font-size:20px;line-height:1.35;font-weight:700;letter-spacing:0;color:#171717;">{escape(story.title)}</h2>
              <div style="font-size:12px;color:#6b7280;margin-bottom:12px;">{escape(story.source_name)} &bull; {escape(_format_date(story.published_at))}</div>
              <p style="margin:0;font-size:15px;line-height:1.65;color:#374151;">{escape(story.summary)}</p>
              {why}
              <div style="margin-top:14px;font-size:13px;">{source_link}</div>
            </td>
          </tr></table>
        </td></tr>"""


def _format_date(value: str) -> str:
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
        return parsed.strftime("%d %b %Y")
    except ValueError:
        return value or "Today"
